#Packages used in the project

library(Matrix)
library(maps)
library(reshape)
library(tidyr)
library(dplyr)
library(reshape2)
library(grid)
library(tree)
library(party)
library(rpart)
library(e1071)
library(MASS)
library(ggplot2)
library(klaR)
library(pROC)

install.packages('devtools')
devtools::install_github('haven-jeon/KoNLP')
library(KoNLP)

myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data1	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data2	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data3	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data4	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data5	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data6	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data7	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data8	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data9	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data10	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data11	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data12	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data13	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data14	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data15	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data16	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data17	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data18	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data19	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data20	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data21	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data22	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data23	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data24	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data25	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data26	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data27	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data28	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data29	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data30	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data31	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data32	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data33	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data34	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data35	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data36	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data37	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data38	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data39	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data40	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data41	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data42	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data43	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data44	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data45	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data46	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data47	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data48	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data49	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data50	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data51	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data52	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data53	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data54	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data55	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data56	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data57	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data58	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data59	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data60	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data61	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data62	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data63	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data64	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data65	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data66	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data67	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data68	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data69	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data70	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data71	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data72	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data73	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data74	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data75	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data76	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data77	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data78	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data79	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data80	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data81	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data82	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data83	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data84	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data85	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data86	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data87	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data88	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data89	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data90	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data91	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data92	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data93	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data94	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data95	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data96	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data97	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data98	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data99	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data100	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data101	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data102	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data103	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data104	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data105	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data106	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data107	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data108	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data109	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data110	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data111	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data112	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data113	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data114	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data115	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data116	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data117	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data118	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data119	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data120	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data121	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data122	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data123	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data124	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data125	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data126	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data127	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data128	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data129	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data130	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data131	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data132	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data133	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data134	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data135	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data136	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data137	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data138	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data139	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data140	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data141	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data142	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data143	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data144	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data145	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data146	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data147	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data148	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data149	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data150	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data151	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data152	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data153	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data154	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data155	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data156	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data157	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data158	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data159	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data160	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data161	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data162	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data163	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data164	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data165	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data166	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data167	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data168	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data169	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data170	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data171	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data172	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data173	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data174	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data175	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data176	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data177	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data178	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data179	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data180	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data181	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data182	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data183	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data184	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data185	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data186	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data187	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data188	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data189	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data190	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data191	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data192	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data193	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data194	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data195	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data196	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data197	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data198	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data199	 <- strsplit(myData,'\n')
myData <- readChar(file.choose(), nchars = 9999, useByte=F)
Data200	 <- strsplit(myData,'\n')

stopWords =c("???", "???", "???", "???", "??????", "???", "??????", "???", "??????", "???", "???", "???", "???", "??????", "???", "??????","1","2","3","4","5","6","7","8","9",",",".",";",":")

Data1new <- ExtractNoun(Data1,stop=stopwords)
Data2new <- ExtractNoun(Data2,stop=stopwords)
Data3new <- ExtractNoun(Data3,stop=stopwords)
Data4new <- ExtractNoun(Data4,stop=stopwords)
Data5new <- ExtractNoun(Data5,stop=stopwords)
Data6new <- ExtractNoun(Data6,stop=stopwords)
Data7new <- ExtractNoun(Data7,stop=stopwords)
Data8new <- ExtractNoun(Data8,stop=stopwords)
Data9new <- ExtractNoun(Data9,stop=stopwords)
Data10new <- ExtractNoun(Data10,stop=stopwords)
Data11new <- ExtractNoun(Data11,stop=stopwords)
Data12new <- ExtractNoun(Data12,stop=stopwords)
Data13new <- ExtractNoun(Data13,stop=stopwords)
Data14new <- ExtractNoun(Data14,stop=stopwords)
Data15new <- ExtractNoun(Data15,stop=stopwords)
Data16new <- ExtractNoun(Data16,stop=stopwords)
Data17new <- ExtractNoun(Data17,stop=stopwords)
Data18new <- ExtractNoun(Data18,stop=stopwords)
Data19new <- ExtractNoun(Data19,stop=stopwords)
Data20new <- ExtractNoun(Data20,stop=stopwords)
Data21new <- ExtractNoun(Data21,stop=stopwords)
Data22new <- ExtractNoun(Data22,stop=stopwords)
Data23new <- ExtractNoun(Data23,stop=stopwords)
Data24new <- ExtractNoun(Data24,stop=stopwords)
Data25new <- ExtractNoun(Data25,stop=stopwords)
Data26new <- ExtractNoun(Data26,stop=stopwords)
Data27new <- ExtractNoun(Data27,stop=stopwords)
Data28new <- ExtractNoun(Data28,stop=stopwords)
Data29new <- ExtractNoun(Data29,stop=stopwords)
Data30new <- ExtractNoun(Data30,stop=stopwords)
Data31new <- ExtractNoun(Data31,stop=stopwords)
Data32new <- ExtractNoun(Data32,stop=stopwords)
Data33new <- ExtractNoun(Data33,stop=stopwords)
Data34new <- ExtractNoun(Data34,stop=stopwords)
Data35new <- ExtractNoun(Data35,stop=stopwords)
Data36new <- ExtractNoun(Data36,stop=stopwords)
Data37new <- ExtractNoun(Data37,stop=stopwords)
Data38new <- ExtractNoun(Data38,stop=stopwords)
Data39new <- ExtractNoun(Data39,stop=stopwords)
Data40new <- ExtractNoun(Data40,stop=stopwords)
Data41new <- ExtractNoun(Data41,stop=stopwords)
Data42new <- ExtractNoun(Data42,stop=stopwords)
Data43new <- ExtractNoun(Data43,stop=stopwords)
Data44new <- ExtractNoun(Data44,stop=stopwords)
Data45new <- ExtractNoun(Data45,stop=stopwords)
Data46new <- ExtractNoun(Data46,stop=stopwords)
Data47new <- ExtractNoun(Data47,stop=stopwords)
Data48new <- ExtractNoun(Data48,stop=stopwords)
Data49new <- ExtractNoun(Data49,stop=stopwords)
Data50new <- ExtractNoun(Data50,stop=stopwords)
Data51new <- ExtractNoun(Data51,stop=stopwords)
Data52new <- ExtractNoun(Data52,stop=stopwords)
Data53new <- ExtractNoun(Data53,stop=stopwords)
Data54new <- ExtractNoun(Data54,stop=stopwords)
Data55new <- ExtractNoun(Data55,stop=stopwords)
Data56new <- ExtractNoun(Data56,stop=stopwords)
Data57new <- ExtractNoun(Data57,stop=stopwords)
Data58new <- ExtractNoun(Data58,stop=stopwords)
Data59new <- ExtractNoun(Data59,stop=stopwords)
Data60new <- ExtractNoun(Data60,stop=stopwords)
Data61new <- ExtractNoun(Data61,stop=stopwords)
Data62new <- ExtractNoun(Data62,stop=stopwords)
Data63new <- ExtractNoun(Data63,stop=stopwords)
Data64new <- ExtractNoun(Data64,stop=stopwords)
Data65new <- ExtractNoun(Data65,stop=stopwords)
Data66new <- ExtractNoun(Data66,stop=stopwords)
Data67new <- ExtractNoun(Data67,stop=stopwords)
Data68new <- ExtractNoun(Data68,stop=stopwords)
Data69new <- ExtractNoun(Data69,stop=stopwords)
Data70new <- ExtractNoun(Data70,stop=stopwords)
Data71new <- ExtractNoun(Data71,stop=stopwords)
Data72new <- ExtractNoun(Data72,stop=stopwords)
Data73new <- ExtractNoun(Data73,stop=stopwords)
Data74new <- ExtractNoun(Data74,stop=stopwords)
Data75new <- ExtractNoun(Data75,stop=stopwords)
Data76new <- ExtractNoun(Data76,stop=stopwords)
Data77new <- ExtractNoun(Data77,stop=stopwords)
Data78new <- ExtractNoun(Data78,stop=stopwords)
Data79new <- ExtractNoun(Data79,stop=stopwords)
Data80new <- ExtractNoun(Data80,stop=stopwords)
Data81new <- ExtractNoun(Data81,stop=stopwords)
Data82new <- ExtractNoun(Data82,stop=stopwords)
Data83new <- ExtractNoun(Data83,stop=stopwords)
Data84new <- ExtractNoun(Data84,stop=stopwords)
Data85new <- ExtractNoun(Data85,stop=stopwords)
Data86new <- ExtractNoun(Data86,stop=stopwords)
Data87new <- ExtractNoun(Data87,stop=stopwords)
Data88new <- ExtractNoun(Data88,stop=stopwords)
Data89new <- ExtractNoun(Data89,stop=stopwords)
Data90new <- ExtractNoun(Data90,stop=stopwords)
Data91new <- ExtractNoun(Data91,stop=stopwords)
Data92new <- ExtractNoun(Data92,stop=stopwords)
Data93new <- ExtractNoun(Data93,stop=stopwords)
Data94new <- ExtractNoun(Data94,stop=stopwords)
Data95new <- ExtractNoun(Data95,stop=stopwords)
Data96new <- ExtractNoun(Data96,stop=stopwords)
Data97new <- ExtractNoun(Data97,stop=stopwords)
Data98new <- ExtractNoun(Data98,stop=stopwords)
Data99new <- ExtractNoun(Data99,stop=stopwords)
Data100new <- ExtractNoun(Data100,stop=stopwords)
Data101new <- ExtractNoun(Data101,stop=stopwords)
Data102new <- ExtractNoun(Data102,stop=stopwords)
Data103new <- ExtractNoun(Data103,stop=stopwords)
Data104new <- ExtractNoun(Data104,stop=stopwords)
Data105new <- ExtractNoun(Data105,stop=stopwords)
Data106new <- ExtractNoun(Data106,stop=stopwords)
Data107new <- ExtractNoun(Data107,stop=stopwords)
Data108new <- ExtractNoun(Data108,stop=stopwords)
Data109new <- ExtractNoun(Data109,stop=stopwords)
Data110new <- ExtractNoun(Data110,stop=stopwords)
Data111new <- ExtractNoun(Data111,stop=stopwords)
Data112new <- ExtractNoun(Data112,stop=stopwords)
Data113new <- ExtractNoun(Data113,stop=stopwords)
Data114new <- ExtractNoun(Data114,stop=stopwords)
Data115new <- ExtractNoun(Data115,stop=stopwords)
Data116new <- ExtractNoun(Data116,stop=stopwords)
Data117new <- ExtractNoun(Data117,stop=stopwords)
Data118new <- ExtractNoun(Data118,stop=stopwords)
Data119new <- ExtractNoun(Data119,stop=stopwords)
Data120new <- ExtractNoun(Data120,stop=stopwords)
Data121new <- ExtractNoun(Data121,stop=stopwords)
Data122new <- ExtractNoun(Data122,stop=stopwords)
Data123new <- ExtractNoun(Data123,stop=stopwords)
Data124new <- ExtractNoun(Data124,stop=stopwords)
Data125new <- ExtractNoun(Data125,stop=stopwords)
Data126new <- ExtractNoun(Data126,stop=stopwords)
Data127new <- ExtractNoun(Data127,stop=stopwords)
Data128new <- ExtractNoun(Data128,stop=stopwords)
Data129new <- ExtractNoun(Data129,stop=stopwords)
Data130new <- ExtractNoun(Data130,stop=stopwords)
Data131new <- ExtractNoun(Data131,stop=stopwords)
Data132new <- ExtractNoun(Data132,stop=stopwords)
Data133new <- ExtractNoun(Data133,stop=stopwords)
Data134new <- ExtractNoun(Data134,stop=stopwords)
Data135new <- ExtractNoun(Data135,stop=stopwords)
Data136new <- ExtractNoun(Data136,stop=stopwords)
Data137new <- ExtractNoun(Data137,stop=stopwords)
Data138new <- ExtractNoun(Data138,stop=stopwords)
Data139new <- ExtractNoun(Data139,stop=stopwords)
Data140new <- ExtractNoun(Data140,stop=stopwords)
Data141new <- ExtractNoun(Data141,stop=stopwords)
Data142new <- ExtractNoun(Data142,stop=stopwords)
Data143new <- ExtractNoun(Data143,stop=stopwords)
Data144new <- ExtractNoun(Data144,stop=stopwords)
Data145new <- ExtractNoun(Data145,stop=stopwords)
Data146new <- ExtractNoun(Data146,stop=stopwords)
Data147new <- ExtractNoun(Data147,stop=stopwords)
Data148new <- ExtractNoun(Data148,stop=stopwords)
Data149new <- ExtractNoun(Data149,stop=stopwords)
Data150new <- ExtractNoun(Data150,stop=stopwords)
Data151new <- ExtractNoun(Data151,stop=stopwords)
Data152new <- ExtractNoun(Data152,stop=stopwords)
Data153new <- ExtractNoun(Data153,stop=stopwords)
Data154new <- ExtractNoun(Data154,stop=stopwords)
Data155new <- ExtractNoun(Data155,stop=stopwords)
Data156new <- ExtractNoun(Data156,stop=stopwords)
Data157new <- ExtractNoun(Data157,stop=stopwords)
Data158new <- ExtractNoun(Data158,stop=stopwords)
Data159new <- ExtractNoun(Data159,stop=stopwords)
Data160new <- ExtractNoun(Data160,stop=stopwords)
Data161new <- ExtractNoun(Data161,stop=stopwords)
Data162new <- ExtractNoun(Data162,stop=stopwords)
Data163new <- ExtractNoun(Data163,stop=stopwords)
Data164new <- ExtractNoun(Data164,stop=stopwords)
Data165new <- ExtractNoun(Data165,stop=stopwords)
Data166new <- ExtractNoun(Data166,stop=stopwords)
Data167new <- ExtractNoun(Data167,stop=stopwords)
Data168new <- ExtractNoun(Data168,stop=stopwords)
Data169new <- ExtractNoun(Data169,stop=stopwords)
Data170new <- ExtractNoun(Data170,stop=stopwords)
Data171new <- ExtractNoun(Data171,stop=stopwords)
Data172new <- ExtractNoun(Data172,stop=stopwords)
Data173new <- ExtractNoun(Data173,stop=stopwords)
Data174new <- ExtractNoun(Data174,stop=stopwords)
Data175new <- ExtractNoun(Data175,stop=stopwords)
Data176new <- ExtractNoun(Data176,stop=stopwords)
Data177new <- ExtractNoun(Data177,stop=stopwords)
Data178new <- ExtractNoun(Data178,stop=stopwords)
Data179new <- ExtractNoun(Data179,stop=stopwords)
Data180new <- ExtractNoun(Data180,stop=stopwords)
Data181new <- ExtractNoun(Data181,stop=stopwords)
Data182new <- ExtractNoun(Data182,stop=stopwords)
Data183new <- ExtractNoun(Data183,stop=stopwords)
Data184new <- ExtractNoun(Data184,stop=stopwords)
Data185new <- ExtractNoun(Data185,stop=stopwords)
Data186new <- ExtractNoun(Data186,stop=stopwords)
Data187new <- ExtractNoun(Data187,stop=stopwords)
Data188new <- ExtractNoun(Data188,stop=stopwords)
Data189new <- ExtractNoun(Data189,stop=stopwords)
Data190new <- ExtractNoun(Data190,stop=stopwords)
Data191new <- ExtractNoun(Data191,stop=stopwords)
Data192new <- ExtractNoun(Data192,stop=stopwords)
Data193new <- ExtractNoun(Data193,stop=stopwords)
Data194new <- ExtractNoun(Data194,stop=stopwords)
Data195new <- ExtractNoun(Data195,stop=stopwords)
Data196new <- ExtractNoun(Data196,stop=stopwords)
Data197new <- ExtractNoun(Data197,stop=stopwords)
Data198new <- ExtractNoun(Data198,stop=stopwords)
Data199new <- ExtractNoun(Data199,stop=stopwords)
Data200new <- ExtractNoun(Data200,stop=stopwords)

data=data.frame()

for (i in 1:200) {
  rbind(data,get(paste0(paste0('Data',i),'new')))
}

temp=data.frame(matrix( nrow = 200, ncol = 1))
for (i in 1:107) {
  temp[i,1]=1
}
for (i in 108:200) {
  temp[i,1]=0
}
colnames(temp)=c("TorF")


data=cbind(temp,data)
getwd()
write.csv(data,file = "newsdata.csv")



